// <auto-generated />
using System;
using ApiUsers.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiUsers.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251007041519_AddTicketTransction")]
    partial class AddTicketTransction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiUsers.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdDept")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdDept");

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("ApiUsers.Models.Dept", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AcceptTicket")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("depts", (string)null);
                });

            modelBuilder.Entity("ApiUsers.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("ApiUsers.Models.StatusTickets", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("statusticket", (string)null);
                });

            modelBuilder.Entity("ApiUsers.Models.Statususer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("statususers", (string)null);
                });

            modelBuilder.Entity("ApiUsers.Models.Tickets", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Id_category")
                        .HasColumnType("int");

                    b.Property<int?>("Id_dept_target")
                        .HasColumnType("int");

                    b.Property<int?>("Id_status")
                        .HasColumnType("int");

                    b.Property<int?>("Id_user")
                        .HasColumnType("int");

                    b.Property<DateTime>("Open_datetime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority_level")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_category");

                    b.HasIndex("Id_dept_target");

                    b.HasIndex("Id_status");

                    b.HasIndex("Id_user");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("ApiUsers.Models.TicketsTransction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Attach_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Id_ticket")
                        .HasColumnType("int");

                    b.Property<int?>("Id_user_source")
                        .HasColumnType("int");

                    b.Property<int?>("Id_user_target")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_ticket");

                    b.HasIndex("Id_user_source");

                    b.HasIndex("Id_user_target");

                    b.ToTable("ticketstransction", (string)null);
                });

            modelBuilder.Entity("ApiUsers.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Blocked")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdDept")
                        .HasColumnType("int");

                    b.Property<int?>("IdProfile")
                        .HasColumnType("int");

                    b.Property<int?>("IdStatus")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pwd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdDept");

                    b.HasIndex("IdProfile");

                    b.HasIndex("IdStatus");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ApiUsers.Models.Category", b =>
                {
                    b.HasOne("ApiUsers.Models.Dept", "IdDeptNavigation")
                        .WithMany("Category")
                        .HasForeignKey("IdDept")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Category_Dept");

                    b.Navigation("IdDeptNavigation");
                });

            modelBuilder.Entity("ApiUsers.Models.Tickets", b =>
                {
                    b.HasOne("ApiUsers.Models.Category", "IdCategoryNavigation")
                        .WithMany("Tickets")
                        .HasForeignKey("Id_category")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Category_Category");

                    b.HasOne("ApiUsers.Models.Dept", "IdDeptNavigation")
                        .WithMany("Tickets")
                        .HasForeignKey("Id_dept_target")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Dept_DeptTicket");

                    b.HasOne("ApiUsers.Models.StatusTickets", "IdStatusTicketsNavigation")
                        .WithMany("Tickets")
                        .HasForeignKey("Id_status")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Status_StatusTicket");

                    b.HasOne("ApiUsers.Models.User", "IdUserNavigation")
                        .WithMany("Tickets")
                        .HasForeignKey("Id_user")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_user_UserTicket");

                    b.Navigation("IdCategoryNavigation");

                    b.Navigation("IdDeptNavigation");

                    b.Navigation("IdStatusTicketsNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("ApiUsers.Models.TicketsTransction", b =>
                {
                    b.HasOne("ApiUsers.Models.Tickets", "TicketNavigation")
                        .WithMany("TicketsTransctions")
                        .HasForeignKey("Id_ticket")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Ticket_TicketTransction");

                    b.HasOne("ApiUsers.Models.User", "UserSource")
                        .WithMany("TicketsSource")
                        .HasForeignKey("Id_user_source")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_UserSource_TicketTransction");

                    b.HasOne("ApiUsers.Models.User", "UserTarget")
                        .WithMany("TicketsTarget")
                        .HasForeignKey("Id_user_target")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_UserTarget_TicketTransction");

                    b.Navigation("TicketNavigation");

                    b.Navigation("UserSource");

                    b.Navigation("UserTarget");
                });

            modelBuilder.Entity("ApiUsers.Models.User", b =>
                {
                    b.HasOne("ApiUsers.Models.Dept", "IdDeptNavigation")
                        .WithMany("Users")
                        .HasForeignKey("IdDept")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Users_Dept");

                    b.HasOne("ApiUsers.Models.Profile", "IdProfileNavigation")
                        .WithMany("Users")
                        .HasForeignKey("IdProfile")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Users_Profile");

                    b.HasOne("ApiUsers.Models.Statususer", "IdStatusNavigation")
                        .WithMany("Users")
                        .HasForeignKey("IdStatus")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Users_Statususer");

                    b.Navigation("IdDeptNavigation");

                    b.Navigation("IdProfileNavigation");

                    b.Navigation("IdStatusNavigation");
                });

            modelBuilder.Entity("ApiUsers.Models.Category", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("ApiUsers.Models.Dept", b =>
                {
                    b.Navigation("Category");

                    b.Navigation("Tickets");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ApiUsers.Models.Profile", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ApiUsers.Models.StatusTickets", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("ApiUsers.Models.Statususer", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ApiUsers.Models.Tickets", b =>
                {
                    b.Navigation("TicketsTransctions");
                });

            modelBuilder.Entity("ApiUsers.Models.User", b =>
                {
                    b.Navigation("Tickets");

                    b.Navigation("TicketsSource");

                    b.Navigation("TicketsTarget");
                });
#pragma warning restore 612, 618
        }
    }
}
